### ISSUE TITLE
build error in interactive_optix

### ISSUE THREAD

**Issue by bigdimboom** [NVIDIA/gvdb-voxels#54]
VS2017
GVDB 1.1
CUDA 10
optix_extra_math.cuh(34): fatal error C1083: Cannot open include file: 'optix.h': No such file or directory

I doubled checked in visual studio optix.h was added to the includes.

All other optix related examples are all working.

**Comment by bigdimboom** [comment]
hint: maybe the example is outdated.
in main_interactive_optix.cpp, the use of "SetMaterialParams" is no  longer valid. SetMaterialParams only takes one argument

**Comment by NeilBickford-NV** [comment]
Hi bigdimboom,

Just wanted to give you a heads-up to let you know that interactive_optix should now build correctly using VS2017, CUDA 10+, and OptiX 6.5 (I may hopefully be working on porting some of the OptiX samples to OptiX 7 soon). The system for linking OptiX also changed a lot in the meantime, so maybe this fixed the issue? Thanks again!
